# Generated by Django 2.0.2 on 2018-02-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_create_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
    ]
