# Generated by Django 2.0.2 on 2018-02-04 03:47

from django.db import migrations
from tenant_schemas.models import TenantMixin
from ..models import Company

def create_public_tenant(apps, schema_editor):
    tenant = Company(
        domain_url='localhost',
        schema_name='public',
        name='Public Tenant',
    )
    tenant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_control', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_public_tenant)
    ]
